POST http://localhost:3001/api/blogs
Content-Type: application/json
User-Agent: vscode-restclient
Accept-Encoding: gzip

{
  "title": "Blogi myös käyttäjän tietoihin?",
  "author": "Jukka Palmukoppa",
  "url": "https://foo.bar.fi",
  "likes": 3
}
###
GET http://localhost:3001/api/blogs
Accept-Encoding: application/json
User-Agent: vscode-restclient
